package UpperModule;

/**
* UpperModule/UpperHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UpperCase.idl
* Thursday, May 7, 2026 7:51:24 AM IST
*/

public final class UpperHolder implements org.omg.CORBA.portable.Streamable
{
  public UpperModule.Upper value = null;

  public UpperHolder ()
  {
  }

  public UpperHolder (UpperModule.Upper initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UpperModule.UpperHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UpperModule.UpperHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UpperModule.UpperHelper.type ();
  }

}
